[package]
name = "libunwind-rs"
version = "0.1.0"
authors = ["fedotoff <fedotoff@ispras.ru>"]
edition = "2018"

[dependencies]
libunwind-sys = "0.3.0"
libc = "0.2.66"
foreign-types = "0.5.0"
num-traits = "0.2"
num-derive = "0.3"
